### ISSUE TITLE
Do we need the changelog ?

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#12]
http://localhost:4000/about/changelog/

**Comment by Sparrow0hawk** [comment]
I'm not wedded to the need to have one and happy to go with the majority on whether to keep it in

Thoughts @callaghanmt @jhodrien @ollie-clark

**Comment by callaghanmt** [comment]
It's not that necessary, is it?  The changelog is baked into the Github repo anyway if anyone wanted to check.

**Comment by NGRhodes** [comment]
Should we have some info on this page (or somewhere else on the site) that points users to the Github repo @ARCLeeds/arcteam ?

**Comment by NGRhodes** [comment]
Fixed in #42
