### ISSUE TITLE
Uploading videos to Youtube channel and then embed them?

### ISSUE THREAD

**Issue by dhvalden** [ARCLeeds/arcleeds.github.io#18]
might be easier to share and maintain and fast loading worldwide.

Obliviously low priority.

**Comment by Sparrow0hawk** [comment]
I think we're slightly prohibited from this by the University. The current way we're providing embedded videos is through Mediasite which is the platform that was advised by the University for uploading content.
We'll keep this suggestion in mind for the future though.

**Comment by dhvalden** [comment]
Fair. I was expecting some kind of restrictions from Uni. Thanks for considering it!
