### ISSUE TITLE
Related Teams outdated.

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#183]
https://arc.leeds.ac.uk/about/team/
This is vastly outdated, It  needs updating or removing.

**Comment by agdturner** [comment]
I've assigned this to myself as I created a new issue for Tom to add a profile. I suppose there are two parts to updating this. One is getting profiles up there for new members, the other is updating the profiles that are already there...

**Comment by agdturner** [comment]
I think this has been sufficiently updated now to close this issue.
