### ISSUE TITLE
External links - new tabs concistancy

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#22]
From BenH:

A minor thing. Some of the external links (such as to service-now) open up new tabs, and others do not. I prefer them to open new tabs...

**Comment by NGRhodes** [comment]
From a usability perspective its generally accepted to not open links in a new tab and let the user decide, should we follow this @ARCLeeds/arcteam ?

**Comment by Sparrow0hawk** [comment]
I think we should follow this as it looks to be accessiblity best practise.
