### ISSUE TITLE
Some of the links still refer to the old website. 

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#23]
From BenH:

Some of the links still refer to the old website.

**Comment by NGRhodes** [comment]
This may be correct if they point to docs, but worth having a check.

**Comment by Sparrow0hawk** [comment]
I've have a quick look through files for references to arc.leeds.ac.uk

![image](https://user-images.githubusercontent.com/20887250/92490931-850b3680-f1e9-11ea-8a8e-b1a03fe2c696.png)

These all seem acceptable for now as its mostly references to Documentation which we haven't yet fully migrated over to arcdocs.

**Comment by NGRhodes** [comment]
Thanks Alex.
