### ISSUE TITLE
Blog: Do we need it ?

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#34]
BenH:
		
- Who's the target audience? Will anyone care? If you guys aren't particularly enjoying doing a blog for it's own sake, I don't think you need it.

**Comment by Sparrow0hawk** [comment]
Content to keep the blog, we just need to get better at generating content for it (a more internal project for the RC team). Commit 0e2a90584005578b8aa53f3fefb5437ae24cd3dc moved an old blog post over from arc.leeds.ac.uk so it has some more content.

**Comment by NGRhodes** [comment]
Thanks Alex.
Agreed, lets keep the blog and commit to updating it.
