### ISSUE TITLE
Community: Events

### ISSUE THREAD

**Issue by NGRhodes** [ARCLeeds/arcleeds.github.io#37]
Benh:

You might want to duplicate the "Events" tab into "Training" as well (as in, just add a duplicated link to the events page in the menu bar).

**Comment by Sparrow0hawk** [comment]
I'm against this suggestion for following reasons:
- The Events page is primarily for directing people towards our Tito ticket registration site for our TechTalks. I'd always envisaged this as a space for events we run that are not training but community orientated reprohacks, hackathons, techtalks, invited speaker talks
- Our training events are managed through the SAP training portal (something that doesn't build nicely into the website) so it feels better to link directly from our training pages to the specific SAP page for registering interest in that event

My main thrust is that the Events page isn't relevant to the training section and so we shouldn't implement this recommendation.

**Comment by NGRhodes** [comment]
Agreed, also seems quite minor in grand scheme of things
